name: qr_creator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  dio: ^5.8.0+1
  flutter_modular: ^6.3.4
  flutter_hooks: ^0.21.2
  gal: ^2.3.1
  path_provider: ^2.1.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
